#!/usr/bin/perl -w
# Convert Gre file to html file.  Supply without suffix
die "Usage: gre2texi file.gre file.texi" if ($#ARGV !=1);
open(IN,  "$ARGV[0]")  || die "Can't open `$ARGV[0]' for input\n";
open(OUT, ">$ARGV[1]") || die "Can't open `$ARGV[1]' for output\n";

print OUT "<html>\n";
$now = localtime;
print OUT "<!- Created $now by $0 from $ARGV[0].gre -->\n" ;
print OUT "<head>\n";
print OUT "<title>$ARGV[0].gre</title>\n";
print OUT "</head>\n";
print OUT "<body>\n";

while(<IN>) {
    s:"([^"]*)":<tt>"$1"</tt>:g;

    s:^if([\s+(]):<b>if</b>$1:g;
    s:(\s+)if([\s+(]):$1<b>if</b>$2:g;

    s:^unless([\s+(]):<b>unless</b>$1:g;
    s:(\s+)unless([\s+(]):$1<b>unless</b>$2:g;

    s:^else(\s+):<b>else</b>$1:g;
    s:(\s+)else(\s+):$1<b>else</b>$2:g;
    s:^for([\s+(]):<b>for</b>$1:g;
    s:(\s+)for([\s+(]):$1<b>for</b>$2:g;
    s:^foreach([\s+(]):<b>foreach</b>$1:g;
    s:(\s+)foreach([\s+(]):$1<b>foreach</b>$2:g;

    s:^while([\s+(]):<b>while</b>$1:g;
    s:(\s+)while([\s+(]):$1<b>while</b>$2:g;

    s:^until([\s+(]):<b>until</b>$1:g;
    s:(\s+)until([\s+(]):$1<b>until</b>$2:g;

    s:^do(\s+):<b>do</b>$1:g;
    s:(\s+)do(\s+):$1<b>do</b>$2:g;
    s:^return([\s+(]):<b>return</b>$1:g;
    s:(\s+)return([\s+(]):$1<b>return</b>$2:g;

    s:^sub(\s+):<b>sub</b>$1:g;
    s:(\s+)sub(\s+):$1<b>sub</b>$2:g;

    s:^cmd(\s+):<b>cmd</b>$1:g;
    s:(\s+)cmd(\s+):$1<b>cmd</b>$2:g;

    s:(\s+)eq(\s+):$1<b>eq</b>$2:g;
    s:(\s+)ne(\s+):$1<b>ne</b>$2:g;
    s:^break(\s+):<b>break</b>$1:g;
    s:(\s+)break(\s+):$1<b>break</b>$2:g;

    # Italicize comments
    s:\$#:KEEP_DOLLAR_POUND:;
    if (/(.*)#(.*)/) {
        $before = $1;
        $comment = $2;
        $comment =~ s:<b>::g;
        $comment =~ s:</b>::g;
        $_ = "$before<i>\#$comment</i>";
    }
    s:KEEP_DOLLAR_POUND:\$#:;

    # Put fixed-width spaces at start.  NOTE: 
    # the tab substitution at the start of this isn't too great,
    # so it's best to 'untabify' the examples first.
    s:^\t:    :g;
    if (/^([ ]*)/) {
        $leader = $1;
        $len = length($leader);
        s:^[ ]*::;
        if ($len > 0) {
	    for ($i = 0; $i < $len; $i++) {
		$_ = "&nbsp;&nbsp;" . $_;
            }
        }
    }
    print OUT "$_<br>\n";
}
print OUT "</body>\n";
print OUT "</html>\n";
