#!/usr/local/bin/perl
# $Id: HTML_subdivide,v 1.3 2000/04/30 15:41:22 kelley Exp $
# Log at end
#
# Special features:
# 1) The item 
#	<!-- newfile filename other_words_for_title -->
#    if it occurs on a line all by itself, causes 
#    this perlscript to chop files here.  The filename
#    will be as specified.  The other_words 
#    will be used as the title.  If neither the
#    filename nor the other_words are present, then
#    this script makes up filenames using numbers, e.g.,
#    gre1.html, gre2.html.  If the filename is ".",
#    then this same naming scheme is used, but the titles
#    are used.
# 2) If the item <!-- occurs on a line all by itself, then
#    this perlscript skips until a line containing --> all
#    by itself is encountered.  This is a kludge because
#    xmosaic refuses to skip comments if a <PRE> item is
#    contained within them.
#
$num_files = 1;
die "Need 2 arg (eg chop_into_subfiles gre.hml \"The Gre graphing language\")" if ($#ARGV != 1);

$basefile = "gre";
$file = "$basefile$num_files.html";
$basetitle = $ARGV[1];
$title = $basetitle;
$marginnote[0] = "Gre";
$#ARGV = 0;			# Dumb way to ignore
print STDOUT "Creating $file\n";
open (OUT, ">$file") || die "Cannot open $file";
$file_list[$num_files++] = $file;

$name_of_top_node = "gre1.html#Top";


print OUT "<html>\n";
print OUT "<head>\n";
print OUT "<title>$title</title>\n";
print OUT "<META NAME=\"author\" CONTENT=\"Dan E. Kelley\">\n";
print OUT "<META NAME=\"keywords\" CONTENT=\"science scientific graphics graph\">\n";
print OUT "<META NAME=\"description\" CONTENT=\"Gre is an extensible plotting language for producing scientific graphs, such as x-y plots, contour plots, and image plots.  It was written by a scientist and therefore has the sorts of things a scientist needs.  It is much like LaTeX, in that it rewards users who climb the learning curve, in a way that GUI-based programs do not.\">\n";
print OUT "</head>\n";



$body_start = "
<body bgcolor=\"#ffffff\" background=\"./resources/sm_bg.gif\" link=\"#993333\" vlink=\"#333399 alink=\"#cc3333\">
";

print OUT "$body_start\n";

while(<>) {
    # Skip comment blocks (kludge; see above)
    if (/^\s*<!--\s*$/) {
	while(<>) {
  	    last if /^\s*-->\s*$/;
        }
	$_ = <>;
    }
    if (/^<[aA] [nN][aA][mM][eE]\s*=\s*"([^"]*)/){ 
	$key = $1;
	$key =~ s/ //g;
        $ref{$key} = "$file#$key";
    }
    if (/^\s*<!--\s* newfile\s* ([^ ]*)\s* "(.*)"\s* "(.*)"\s*-->\s*$/) {
        $file = (length($1) > 0 && $1 ne ".")
	    ? $1 : "$basefile$num_files.html";
	if (length($2) > 0) {
	    $title = $2;
	} else {
	    $title = $basetitle;
	}
        if (length($3) > 0) {
	    $marginnote[$num_files] = $3;
	}

	print OUT "<p>\n";
	print OUT "(c) 1997-2000 Dan E. Kelley, email <a href=\"mailto:Dan.Kelley\@Dal.Ca\">
Dan.Kelley\@Dal.Ca</a>
</tr>
<p>
</table>
<img src=\"./resources/bottom_banner.gif\" HEIGHT=\"26\" WIDTH=\"603\" usemap=\"#navigate_bottom\" border=\"0\">
";
	close OUT;
	open (OUT, ">$file") || die "Cannot open $file";
	$file_list[$num_files++] = $file;
	print OUT "<html>\n";
	print OUT "<head>\n";
        print OUT "<title>$title</title>\n";
        print OUT "</head>\n";
	print OUT "$body_start\n";
        print "Creating $file\n";
    }
    print OUT;
} 
close OUT;

for ($i = 1; $i < $num_files; $i++) {
    $file = $file_list[$i];
    $ofile = "$file.pass2";
    open (IN, "$file") || die "Cannot open $file";
    open (PASS2, ">$ofile") || die "Cannot open $ofile";
    print "$file .";
    $node_parent = "";
    $need_to_find_parent = 1;
    while(<IN>) {
        if (/\s*href\s*=\s*"#([^"]*)/i) {
            $key = $1;		# suck out key
	    $key =~ s/ //g;	# despace key
	    s,"#[^"]*,"$ref{$key},;	# replace key with what is keyed to
            s,="#,=",;
        } elsif (/<a\s*name\s*=\s*"([^"]*)/i) {
            # <a name="foo bar">
	    $key = $1;
	    $key =~ s/ //g;
	    s,"[^"]*","$key",;
       }
       if ($need_to_find_parent && /a href="([^"]*)">parent/) {
           $need_to_find_parent = 0;
           $node_parent = $1;
       }
       # Do not print those 'Navigation' things
       if (!/^<b>Navigation<\/b>:/ 
	   && !/<a href=".*">next<\/a>,/
	   && !/<a href=".*">previous<\/a>,/
	   && !/<a href=".*">previous<\/a>,/
	   && !/<a href=".*">parent<\/a>/) {
	   print PASS2 if (!/href=""/);
       }
    }
    print ".";
    close IN;
    close PASS2;
    open (PASS3, ">$file.pass3") || die "Cannot open $file.pass3";
    open (PASS2, "$file.pass2")  || die "Cannot open $file.pass2";
    $need_table_cmd = 1;
    while(<PASS2>) {
        if (/^<\s*a\s*name="(.*)"\s*>/ && $need_table_cmd) {
            $need_table_cmd = 0;
            print PASS3;
	    $this_chapter = $marginnote[$i];
	    if ($this_chapter eq "") {
		$this_chapter = "Gre";
	    }
            print PASS3 "
<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">
<tr>
<td colspan=2><img src=\"./resources/top_banner.gif\" HEIGHT=\"28\" WIDTH=\"604\" usemap=\"#navigate_top\" border=\"0\"></td></tr>
<tr>
<td width=\"150\" valign=\"top\">
<font size=+1>
<i>$this_chapter</i>
</font>
<font size=-1>
<p>
<clear>
<a href=\"Introduction.html\" ONMOUSEOVER=\"window.status='Beginners -- start reading here';return true\">1: Introduction</a><br>
<a href=\"Invoking.html\" ONMOUSEOVER=\"window.status='Beginners -- start reading here';return true\">2: Invoking Gre</a><br>
<a href=\"Grammar.html\" ONMOUSEOVER=\"window.status='Full description of Gre grammar';return true\">3: Gre Grammar</a><br>
<a href=\"BuiltinCommands.html\" ONMOUSEOVER=\"window.status='Full list of Gre commands';return true\">4: Commands</a><br>
<a href=\"Cookbook.html\" ONMOUSEOVER=\"window.status='Some complicated real-world applications';return true\">5: Cookbook</a><br>
<a href=\"Hints.html\" ONMOUSEOVER=\"window.status='Some hints for Gre programming';return true\">6: Hints</a><br>
<a href=\"History.html\" ONMOUSEOVER=\"window.status='How Gre has evolved (check here for updates)';return true\">7: History</a><br>
<a href=\"Plans.html\" ONMOUSEOVER=\"window.status='Plans for Gre';return true\">8: Plans</a><br>
<a href=\"ConceptIndex.html\" ONMOUSEOVER=\"window.status='Fully-linked index';return true\"><b>9: Concept Index</a></b>
</font></td>
<td width=\"500\" valign=\"top\">
";
            if ($file ne "gre1.html") {
                print PASS3 "<map name=\"navigate_top\">\n";
		print PASS3 "<area shape=\"rect\" coords=\"5,2,218,24\" href=\"$name_of_top_node\">\n";
		if ($node_parent ne "") {
		    print PASS3 "<area shape=\"rect\" coords=\"515,2,535,24\" href=\"$node_parent\">\n";
		}
		print PASS3 "<area shape=\"rect\" coords=\"550,2,575,24\" href=\"",
		    $file_list[$i-1], "\">\n";
		print PASS3 "<area shape=\"rect\" coords=\"580,2,600,24\" href=\"",
		    $file_list[$i+1], "\">\n";
		print PASS3 "</map>\n";
		print PASS3 "<map name=\"navigate_bottom\">\n";
		print PASS3 "<area shape=\"rect\" coords=\"5,2,218,24\" href=\"",
	            $name_of_top_node, "\">\n";
	        print PASS3 "<area shape=\"rect\" coords=\"580,2,600,24\" href=\"",
		    $file_list[$i+1], "\"></map>\n";
		print PASS3 "</map>\n";
            }
        } else {
            print PASS3;
        }
    }
    close(PASS2);
    print PASS3 "
</table>
</body>
</html>
";
    close(PASS3);
    unlink("$file.pass2");
    rename("$file.pass3", "$file");
    print ".\n";
}

# $Log: HTML_subdivide,v $
# Revision 1.3  2000/04/30 15:41:22  kelley
# *** empty log message ***
#
# Revision 1.2  1999/05/22 14:37:07  kelley
# Some language changes, and also fix @xref in the texinfo, so that can create first version for redhat 6.x.
#
# Revision 1.1.1.1  1998/08/03 15:57:26  kelley
# gre-0.1.15
#
# Revision 1.1.1.1  1998/08/03 14:19:45  kelley
# gre-0.1.15
#
# Revision 1.19  1998/07/01  15:30:42  kelley
# *** empty log message ***
#
# Revision 1.18  1998/07/01  15:22:09  kelley
# *** empty log message ***
#
# Revision 1.17  1998/02/03  22:19:34  kelley
# *** empty log message ***
#
# Revision 1.16  1998/02/03  22:16:04  kelley
# *** empty log message ***
#
# Revision 1.15  1997/09/04  14:04:49  kelley
# *** empty log message ***
#
# Revision 1.14  1997/07/24  13:06:30  kelley
# *** empty log message ***
#
# Revision 1.13  1997/07/16  17:44:45  kelley
# *** empty log message ***
#
# Revision 1.12  1997/07/16  17:43:31  kelley
# *** empty log message ***
#
# Revision 1.11  1997/07/12  13:07:44  kelley
# *** empty log message ***
#
# Revision 1.10  1997/07/07  12:51:41  kelley
# *** empty log message ***
#
# Revision 1.9  1997/05/17  15:14:42  kelley
# *** empty log message ***
#
# Revision 1.8  1997/05/17  14:48:06  kelley
# *** empty log message ***
#
# Revision 1.7  1997/05/15  16:06:31  kelley
# *** empty log message ***
#
# Revision 1.6  1997/05/15  15:45:27  kelley
# *** empty log message ***
#
# Revision 1.5  1997/05/15  15:22:05  kelley
# *** empty log message ***
#
# Revision 1.4  1997/05/15  15:16:40  kelley
# *** empty log message ***
#
# Revision 1.3  1997/05/15  15:07:36  kelley
# unlink
#
# Revision 1.2  1997/05/15  13:19:04  kelley
# Major changes -- copy from gri version
#

